"""ClawLock v1.1.0 report renderer - Rich terminal + JSON + HTML output."""

from __future__ import annotations

import html as html_mod
import json
from datetime import datetime
from pathlib import Path
from typing import Optional

from rich import box
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from ..scanners import CRIT, HIGH, WARN

console = Console()


def _level_badge(level: str) -> Text:
    if level in (CRIT, HIGH):
        return Text("High", style="bold red")
    if level == WARN:
        return Text("Warn", style="bold yellow")
    return Text("Info", style="dim")


def _status_icon(findings) -> str:
    if any(f.level in (CRIT, HIGH) for f in findings):
        return "Risk"
    if any(f.level == WARN for f in findings):
        return "Review"
    return "Pass"


def _status_style(status: str) -> str:
    if status == "Risk":
        return "bold red"
    if status == "Review":
        return "bold yellow"
    return "bold green"


def render_scan_report(
    adapter_name,
    adapter_version,
    all_findings_map: dict,
    output_format="text",
    output_path: Optional[str] = None,
):
    """Render scan results in text, JSON, or HTML."""
    t = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    all_f = [f for fs in all_findings_map.values() for f in fs]
    nc = sum(1 for f in all_f if f.level in (CRIT, HIGH))
    nw = sum(1 for f in all_f if f.level == WARN)
    score = max(0, 100 - nc * 20 - nw * 5)

    from ..utils import device_fingerprint, record_scan

    dev_fp = device_fingerprint()
    record_scan(adapter_name, score, nc, nw, len(all_f))

    if output_format == "json":
        out = {
            "tool": "ClawLock",
            "version": "1.1.0",
            "time": t,
            "adapter": adapter_name,
            "device": dev_fp,
            "score": score,
            "findings": [
                {
                    "scanner": f.scanner,
                    "level": f.level,
                    "title": f.title,
                    "detail": f.detail,
                    "location": f.location,
                    "remediation": f.remediation,
                }
                for f in all_f
            ],
        }
        text = json.dumps(out, ensure_ascii=False, indent=2)
        if output_path:
            Path(output_path).write_text(text, encoding="utf-8")
            console.print(f"[green]Saved JSON report: {output_path}[/green]")
        else:
            console.print_json(text)
        return

    if output_format == "html":
        _render_html(
            adapter_name,
            adapter_version,
            t,
            score,
            nc,
            nw,
            all_findings_map,
            output_path,
        )
        return

    console.print()
    console.print(
        Panel(
            "[bold]ClawLock Security Report[/bold]",
            subtitle=f"Time {t}  |  Adapter {adapter_name} {adapter_version}  |  Device {dev_fp}",
            border_style="cyan",
        )
    )
    sc = "red" if score < 60 else ("yellow" if score < 80 else "green")
    console.print(
        f"  Score [bold {sc}]{score}/100[/bold {sc}]"
        f"  |  [red]High {nc}[/red]"
        f"  |  [yellow]Warn {nw}[/yellow]"
    )
    console.print()

    summary = Table(box=box.ROUNDED, show_header=True, header_style="bold cyan")
    summary.add_column("Check", min_width=14)
    summary.add_column("Status", min_width=12)
    summary.add_column("Summary", min_width=40)
    for label, fs in all_findings_map.items():
        status = _status_icon(fs) if fs else "Pass"
        high_count = len([f for f in fs if f.level in (CRIT, HIGH)])
        warn_count = len([f for f in fs if f.level == WARN])
        summary.add_row(
            label,
            Text(status, style=_status_style(status)),
            f"{high_count} high, {warn_count} warn" if fs else "no issue found",
        )
    console.print(summary)
    console.print()

    step = 0
    for label, fs in all_findings_map.items():
        step += 1
        if not fs:
            continue
        console.print(f"[bold cyan]Step {step}: {label}[/bold cyan]")
        tbl = Table(box=box.SIMPLE, show_header=True, header_style="bold")
        tbl.add_column("Level", min_width=10)
        tbl.add_column("Finding", min_width=30)
        tbl.add_column("Detail", min_width=40)
        for f in fs:
            tbl.add_row(_level_badge(f.level), f.title[:60], f.detail[:80])
        console.print(tbl)
        for f in fs[:3]:
            if f.remediation:
                console.print(f"  [dim]Fix: {f.remediation}[/dim]")
        console.print()

    console.print(
        Panel(
            "[dim]Generated by ClawLock v1.1.0. Static analysis reflects the currently visible code and config only.[/dim]",
            border_style="dim",
        )
    )


def _render_html(
    adapter_name, adapter_version, t, score, nc, nw, all_findings_map, output_path
):
    """Generate a standalone HTML report."""
    sc = "#e24b4a" if score < 60 else ("#ef9f27" if score < 80 else "#1d9e75")
    rows = ""
    for label, fs in all_findings_map.items():
        if not fs:
            continue
        for f in fs:
            lv_color = (
                "#e24b4a"
                if f.level in (CRIT, HIGH)
                else ("#ef9f27" if f.level == WARN else "#888")
            )
            lv_text = (
                "High"
                if f.level in (CRIT, HIGH)
                else ("Warn" if f.level == WARN else "Info")
            )
            rows += (
                "<tr>"
                f'<td style="text-align:center"><span style="background:{lv_color};color:#fff;padding:2px 8px;border-radius:4px;font-size:12px">{lv_text}</span></td>'
                f"<td>{html_mod.escape(label)}</td>"
                f'<td><b>{html_mod.escape(f.title[:80])}</b><br><span style="color:#666;font-size:13px">{html_mod.escape(f.detail[:120])}</span></td>'
                f'<td style="font-size:13px">{html_mod.escape(f.remediation[:100])}</td></tr>\n'
            )
    html_content = f"""<!DOCTYPE html><html><head><meta charset="utf-8"><title>ClawLock Security Report</title>
<style>body{{font-family:-apple-system,sans-serif;max-width:960px;margin:40px auto;padding:0 20px;color:#333;background:#fafaf8}}
h1{{color:#222;border-bottom:2px solid #ddd;padding-bottom:12px}}
.score{{display:inline-block;font-size:36px;font-weight:700;color:{sc};margin:8px 0}}
.meta{{color:#888;font-size:14px}}
table{{width:100%;border-collapse:collapse;margin:20px 0}}
th{{background:#f5f5f0;text-align:left;padding:10px;border-bottom:2px solid #ddd;font-size:13px}}
td{{padding:10px;border-bottom:1px solid #eee;vertical-align:top}}
tr:hover{{background:#f9f9f4}}
.footer{{margin-top:40px;padding:16px;background:#f5f5f0;border-radius:8px;font-size:13px;color:#888;text-align:center}}
</style></head><body>
<h1>ClawLock Security Report</h1>
<p class="meta">Time {t} &nbsp; Adapter {adapter_name} {adapter_version}</p>
<p>Score <span class="score">{score}/100</span> &nbsp; High {nc} &nbsp; Warn {nw}</p>
<table><thead><tr><th style="width:80px">Level</th><th style="width:120px">Check</th><th>Finding</th><th style="width:200px">Fix</th></tr></thead>
<tbody>{rows}</tbody></table>
<div class="footer">Generated by ClawLock v1.1.0 | <a href="https://github.com/g1at/clawlock">github.com/g1at/clawlock</a><br>
Static analysis reflects the currently visible code and config only.</div></body></html>"""
    out = Path(output_path or "clawlock-report.html")
    out.write_text(html_content, encoding="utf-8")
    console.print(f"[green]Saved HTML report: {out.absolute()}[/green]")
    import webbrowser

    try:
        webbrowser.open(f"file://{out.absolute()}")
    except Exception:
        pass
